name: Deploy Pages

on:
  push:
    # Runs on pushes targeting the default branch
    branches: [$default-branch]
    # And touched pkgs/**
    paths:
      - 'pkgs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: 28.1
      - name: Build packages metadata
        run: |
          mkdir -p docs/build
          nix --experimental-features 'nix-command flakes' eval --verbose '.#pkgs-metas' --json > docs/build/packages.json
          python3 tools/convert_to_org.py docs/build/packages.json > docs/build/packages.org
      - name: Build HTML output
        run: |
          emacs --batch -l docs/make-html.el --kill
          mkdir -p docs/build/html
          cp docs/index.html docs/style.css docs/build/html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

# vim:ts=2:sw=2:et
